var namespaceArchUnitNET_1_1Fluent_1_1Exceptions =
[
    [ "CannotGetObjectsOfCombinedArchRuleCreatorException", "classArchUnitNET_1_1Fluent_1_1Exceptions_1_1CannotGetObjectsOfCombinedArchRuleCreatorException.html", "classArchUnitNET_1_1Fluent_1_1Exceptions_1_1CannotGetObjectsOfCombinedArchRuleCreatorException" ],
    [ "CannotGetObjectsOfCombinedArchRuleException", "classArchUnitNET_1_1Fluent_1_1Exceptions_1_1CannotGetObjectsOfCombinedArchRuleException.html", "classArchUnitNET_1_1Fluent_1_1Exceptions_1_1CannotGetObjectsOfCombinedArchRuleException" ]
];