//  Copyright 2019 Florian Gather <florian.gather@tngtech.com>
// 	Copyright 2019 Fritz Brandhuber <fritz.brandhuber@tngtech.com>
// 	Copyright 2020 Pavel Fischer <rubbiroid@gmail.com>
// 
// 	SPDX-License-Identifier: Apache-2.0
// 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using ArchUnitNET.Domain;
using ArchUnitNET.Domain.PlantUml.Export;
using ArchUnitNET.Fluent;
using ArchUnitNET.Fluent.Slices;
using ArchUnitNET.Loader;
using Snapper;
using TestAssembly;
using Xunit;
using static ArchUnitNET.Fluent.PlantUml.PlantUmlDefinition;

namespace ArchUnitNETTests.Fluent.PlantUml
{
    public class PlantUmlFluentComponentDiagramTests
    {
        private static readonly Architecture Architecture =
            new ArchLoader().LoadAssembly(typeof(PlantUmlFluentComponentDiagramTests).Assembly).Build();
        private static readonly Architecture Architecture1 = 
            new ArchLoader().LoadAssembly(typeof(Class1).Assembly).Build();
        private static readonly List<IPlantUmlElement> Dependencies = new List<IPlantUmlElement>
        {
            new PlantUmlDependency("a", "b", DependencyType.OneToOne),
            new PlantUmlDependency("b", "c", DependencyType.OneToOne),
            new PlantUmlDependency("c", "a", DependencyType.OneToOne)
        };

        [Fact]
        public void ComponentDiagramFromSlicesTest()
        {
            var sliceRule = SliceRuleDefinition.Slices().Matching("ArchUnitNETTests.(*).");
            var sliceRule1 = SliceRuleDefinition.Slices().Matching("TestAssembly.(*).");
            
            var uml1 = ComponentDiagram().WithDependenciesFromSlices(sliceRule, Architecture).AsString();
            var uml2 = ComponentDiagram().WithDependenciesFromSlices(sliceRule1.GetObjects(Architecture1), sliceRule.GetObjects(Architecture)).AsString();
            var uml3 = ComponentDiagram().WithDependenciesFromSlices(sliceRule.GetObjects(Architecture)).AsString();
           
            Assert.NotEmpty(uml1);
            Assert.NotEmpty(uml2);
            Assert.NotEmpty(uml3);
        }
        
        [Fact]
        public void ComponentDiagramFromSlicesBuild()
        {
            var sliceRule1 = SliceRuleDefinition.Slices().Matching("Microsoft.VisualStudio.TestPlatform.(**).");
            var arch1 = new ArchLoader()
                .LoadAssembly(typeof(Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode).Assembly).Build();
            var path1 = "../../../Fluent/PlantUml/BuildTest/Test1.puml";
            ComponentDiagram().WithDependenciesFromSlices(sliceRule1, arch1).WriteToFile(path1);
            Assert.True(File.Exists(path1));
            
            var sliceRule2 = SliceRuleDefinition.Slices().Matching("Snapper.(**).");
            var arch2 = new ArchLoader()
                .LoadAssembly(typeof(Snapper.SnapperExtensions).Assembly).Build();
            var path2 = "../../../Fluent/PlantUml/BuildTest/Test2.puml";
            ComponentDiagram().WithDependenciesFromSlices(sliceRule2, arch2).WriteToFile(path2);
            Assert.True(File.Exists(path2));
            
            
            var path3 = "../../../Fluent/PlantUml/BuildTest/Test3.puml";
            ComponentDiagram().WithDependenciesFromSlices(sliceRule1.GetObjects(arch1), sliceRule2.GetObjects(arch2)).WriteToFile(path3);
            Assert.True(File.Exists(path3));

        }

        [Fact]
        public void ComponentDiagramFromTypesTest()
        {
            var typeRule = ArchRuleDefinition.Types().That().Are(typeof(PlantUmlFluentComponentDiagramTests));
            var uml1 = ComponentDiagram().WithDependenciesFromTypes(typeRule, Architecture)
                .AsString(new RenderOptions {OmitClassFields = true});
            var uml2 = ComponentDiagram().WithDependenciesFromTypes(typeRule.GetObjects(Architecture))
                .AsString(new RenderOptions {OmitClassFields = true});
            var uml3 = ComponentDiagram()
                .WithDependenciesFromTypes(typeRule, Architecture,
                    new GenerationOptions {IncludeDependenciesToOther = true}).AsString();
            var uml4 = ComponentDiagram().WithDependenciesFromTypes(typeRule.GetObjects(Architecture),
                new GenerationOptions {IncludeDependenciesToOther = true}).AsString();
            Assert.NotEmpty(uml1);
            Assert.NotEmpty(uml2);
            Assert.NotEmpty(uml3);
            Assert.NotEmpty(uml4);
            var expectedUml = "@startuml" + Environment.NewLine + "class \"" +
                              typeof(PlantUmlFluentComponentDiagramTests).FullName +
                              "\" {" + Environment.NewLine + "}" + Environment.NewLine + "@enduml" + Environment.NewLine;
            Assert.Equal(expectedUml, uml1);
            Assert.Equal(expectedUml, uml2);
        }

        [Fact]
        public void ComponentDiagramFromCustomDependenciesTest()
        {
            var classesWithoutDependencies = new[] {new PlantUmlClass("d")};
            var uml = ComponentDiagram().WithElements(Dependencies.Concat(classesWithoutDependencies)).AsString();
            Assert.NotEmpty(uml);
            uml.ShouldMatchSnapshot();
        }

        [Fact]
        public void ComponentDiagramWriteToFileTest()
        {
            var classesWithoutDependencies = new[] {new PlantUmlClass("d")};
            const string path = "temp/testUml.puml";
            ComponentDiagram().WithElements(Dependencies.Concat(classesWithoutDependencies)).WriteToFile(path);
            Assert.True(File.Exists(path));

            using (var sr = File.OpenText(path))
            {
                var s = sr.ReadToEnd();
                s.ShouldMatchSnapshot();
            }

            File.Delete(path);

            if (!Directory.EnumerateFileSystemEntries("temp").Any())
            {
                Directory.Delete("temp");
            }
        }
    }
}