@startuml
[Loader]
[Fluent]
[Domain]
[Dependencies]
[ArchitectureTests]
[Loader] --|> [Fluent]
[Loader] --|> [Domain]
[Fluent] --|> [Domain]
[Domain] --|> [Loader]
[Domain] --|> [Fluent]
[Domain] --|> [Dependencies]
[Dependencies] --|> [Domain]
@enduml
