@startuml
package ArchUnitNET{
package Fluent{
package Syntax{
package Elements{
package Types{

}
}
}
}
}
package ArchUnitNET{
package Fluent{
package Syntax{
package Elements{
package Members{

}
}
}
}
}
package ArchUnitNET{
package Fluent{
package Syntax{
package Elements{
package Members{
[PropertyMembers] as ArchUnitNET.Fluent.Syntax.Elements.Members.PropertyMembers
}
}
}
}
}
package ArchUnitNET{
package Fluent{
package Syntax{
package Elements{
package Members{
[MethodMembers] as ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers
}
}
}
}
}
package ArchUnitNET{
package Fluent{
package Syntax{
package Elements{
package Members{
[FieldMembers] as ArchUnitNET.Fluent.Syntax.Elements.Members.FieldMembers
}
}
}
}
}
package ArchUnitNET{
package Fluent{
[Predicates] as ArchUnitNET.Fluent.Predicates
}
}
package ArchUnitNET{
package Fluent{
[Conditions] as ArchUnitNET.Fluent.Conditions
}
}
package ArchUnitNET{
package Domain{

}
}
package ArchUnitNET{
package Domain{
[Extensions] as ArchUnitNET.Domain.Extensions
}
}
package ArchUnitNET{
package Domain{
[Exceptions] as ArchUnitNET.Domain.Exceptions
}
}
package ArchUnitNET{
package Domain{
[Dependencies] as ArchUnitNET.Domain.Dependencies
}
}
Members -[#green]> Types
[ArchUnitNET.Fluent.Syntax.Elements.Members.PropertyMembers] --|> [ArchUnitNET.Fluent.Predicates]
[ArchUnitNET.Fluent.Syntax.Elements.Members.PropertyMembers] --|> [ArchUnitNET.Fluent.Conditions]
[ArchUnitNET.Fluent.Syntax.Elements.Members.PropertyMembers] -[#red]> Domain
[ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers] --|> [ArchUnitNET.Fluent.Predicates]
[ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers] --|> [ArchUnitNET.Fluent.Conditions]
[ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers] --|> [ArchUnitNET.Domain.Extensions]
[ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers] --|> [ArchUnitNET.Domain.Exceptions]
[ArchUnitNET.Fluent.Syntax.Elements.Members.MethodMembers] --|> [ArchUnitNET.Domain.Dependencies]
[ArchUnitNET.Fluent.Syntax.Elements.Members.FieldMembers] -[#red]> Domain
@enduml
