using System.Collections.Generic;
using ArchUnitNET.Fluent;
using Xunit;
using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace ArchUnitNETTests.Fluent.Syntax.Elements;

public class ObjectsShouldVisibilityTests
{
    [Fact]
    public void VisibilityTest()
    {
        var visibilityRules = new List<IArchRule>
        {
            Types().That().ArePrivate().Should().BePrivate(),
            Types().That().ArePublic().Should().BePublic(),
            Types().That().AreProtected().Should().BeProtected(),
            Types().That().AreInternal().Should().BeInternal(),
            Types().That().AreProtectedInternal().Should().BeProtectedInternal(),
            Types().That().ArePrivateProtected().Should().BePrivateProtected(),
            Types().That().AreNotPrivate().Should().NotBePrivate(),
            Types().That().AreNotPublic().Should().NotBePublic(),
            Types().That().AreNotProtected().Should().NotBeProtected(),
            Types().That().AreNotInternal().Should().NotBeInternal(),
            Types().That().AreNotProtectedInternal().Should().NotBeProtectedInternal(),
            Types().That().AreNotPrivateProtected().Should().NotBePrivateProtected(),
            Types()
                .That()
                .ArePrivate()
                .Should()
                .NotBePublic()
                .AndShould()
                .NotBeProtected()
                .AndShould()
                .NotBeInternal()
                .AndShould()
                .NotBeProtectedInternal()
                .AndShould()
                .NotBePrivateProtected(),
            Types()
                .That()
                .ArePublic()
                .Should()
                .NotBePrivate()
                .AndShould()
                .NotBeProtected()
                .AndShould()
                .NotBeInternal()
                .AndShould()
                .NotBeProtectedInternal()
                .AndShould()
                .NotBePrivateProtected(),
            Types()
                .That()
                .AreProtected()
                .Should()
                .NotBePublic()
                .AndShould()
                .NotBePrivate()
                .AndShould()
                .NotBeInternal()
                .AndShould()
                .NotBeProtectedInternal()
                .AndShould()
                .NotBePrivateProtected(),
            Types()
                .That()
                .AreInternal()
                .Should()
                .NotBePublic()
                .AndShould()
                .NotBeProtected()
                .AndShould()
                .NotBePrivate()
                .AndShould()
                .NotBeProtectedInternal()
                .AndShould()
                .NotBePrivateProtected(),
            Types()
                .That()
                .AreProtectedInternal()
                .Should()
                .NotBePublic()
                .AndShould()
                .NotBeProtected()
                .AndShould()
                .NotBeInternal()
                .AndShould()
                .NotBePrivate()
                .AndShould()
                .NotBePrivateProtected(),
            Types()
                .That()
                .ArePrivateProtected()
                .Should()
                .NotBePublic()
                .AndShould()
                .NotBeProtected()
                .AndShould()
                .NotBeInternal()
                .AndShould()
                .NotBeProtectedInternal()
                .AndShould()
                .NotBePrivate(),
            Types()
                .That()
                .AreNotPrivate()
                .Should()
                .BePublic()
                .OrShould()
                .BeProtected()
                .OrShould()
                .BeInternal()
                .OrShould()
                .BeProtectedInternal()
                .OrShould()
                .BePrivateProtected(),
            Types()
                .That()
                .AreNotPublic()
                .Should()
                .BePrivate()
                .OrShould()
                .BeProtected()
                .OrShould()
                .BeInternal()
                .OrShould()
                .BeProtectedInternal()
                .OrShould()
                .BePrivateProtected(),
            Types()
                .That()
                .AreNotProtected()
                .Should()
                .BePublic()
                .OrShould()
                .BePrivate()
                .OrShould()
                .BeInternal()
                .OrShould()
                .BeProtectedInternal()
                .OrShould()
                .BePrivateProtected(),
            Types()
                .That()
                .AreNotInternal()
                .Should()
                .BePublic()
                .OrShould()
                .BeProtected()
                .OrShould()
                .BePrivate()
                .OrShould()
                .BeProtectedInternal()
                .OrShould()
                .BePrivateProtected(),
            Types()
                .That()
                .AreNotProtectedInternal()
                .Should()
                .BePublic()
                .OrShould()
                .BeProtected()
                .OrShould()
                .BeInternal()
                .OrShould()
                .BePrivate()
                .OrShould()
                .BePrivateProtected(),
            Types()
                .That()
                .AreNotPrivateProtected()
                .Should()
                .BePublic()
                .OrShould()
                .BeProtected()
                .OrShould()
                .BeInternal()
                .OrShould()
                .BeProtectedInternal()
                .OrShould()
                .BePrivate(),
        };

        foreach (var visibilityRule in visibilityRules)
        {
            Assert.True(
                visibilityRule.HasNoViolations(StaticTestArchitectures.VisibilityArchitecture)
            );
        }
    }
}
