@startuml
[PlantUml.Import] --|> [PlantUml.Exceptions]
[PlantUml.Import] --|> [Extensions]
[PlantUml.Export] --|> [PlantUml.Exceptions]
[PlantUml.Export] --|> [Extensions]
[PlantUml.Export] --|> [Dependencies]
[Extensions] --|> [Exceptions]
[Extensions] --|> [Dependencies]
@enduml
