@startuml
[ObjectModel] --|> [ObjectModel.Utilities]
[ObjectModel] --|> [ObjectModel.Resources]
[ObjectModel] --|> [ObjectModel.Navigation]
[ObjectModel] --|> [ObjectModel.Client]
[ObjectModel.Utilities] --|> [ObjectModel]
[ObjectModel.Utilities] --|> [ObjectModel.Resources]
[ObjectModel.Navigation] --|> [ObjectModel]
[ObjectModel.Navigation] --|> [ObjectModel.Resources]
[ObjectModel.Logging] --|> [ObjectModel]
[ObjectModel.Host] --|> [ObjectModel]
[ObjectModel.Host] --|> [ObjectModel.Logging]
[ObjectModel.Host] --|> [ObjectModel.Client.Interfaces]
[ObjectModel.InProcDataCollector] --|> [ObjectModel.DataCollector.InProcDataCollector]
[ObjectModel.InProcDataCollector] --|> [ObjectModel.DataCollection]
[ObjectModel.DataCollector.InProcDataCollector] --|> [ObjectModel]
[ObjectModel.DataCollector.InProcDataCollector] --|> [ObjectModel.DataCollection]
[ObjectModel.DataCollection] --|> [ObjectModel]
[ObjectModel.DataCollection] --|> [ObjectModel.Resources]
[ObjectModel.DataCollection] --|> [ObjectModel.Logging]
[ObjectModel.Client] --|> [ObjectModel]
[ObjectModel.Client] --|> [ObjectModel.Resources]
[ObjectModel.Client] --|> [ObjectModel.Logging]
[ObjectModel.Client] --|> [ObjectModel.Client.Interfaces]
[ObjectModel.Client.Payloads] --|> [ObjectModel.Client]
[ObjectModel.Client.Interfaces] --|> [ObjectModel]
[ObjectModel.Adapter] --|> [ObjectModel]
[ObjectModel.Adapter] --|> [ObjectModel.Logging]
@enduml
