@startuml
[Json] --|> [Exceptions]
[Json] --|> [Core]
[Exceptions] --|> [Core]
[Core] --|> [Json]
[Core] --|> [Exceptions]
[Core] --|> [Core.TestMethodResolver]
[Core] --|> [Core.TestMethodResolver.TestMethods]
[Core] --|> [Attributes]
[Core.TestMethodResolver] --|> [Exceptions]
[Core.TestMethodResolver] --|> [Core.TestMethodResolver.TestMethods]
@enduml
