@startuml
[Runtime] --|> [Numerics]
[Runtime] --|> [Globalization]
[Runtime] --|> [ComponentModel]
[Runtime] --|> [CodeDom]
[Runtime] --|> [Buffers]
[Runtime] --|> [Threading]
[Runtime] --|> [Text]
[Runtime] --|> [StubHelpers]
[Runtime] --|> [Security]
[Runtime] --|> [Reflection]
[Runtime] --|> [IO]
[Runtime] --|> [Diagnostics]
[Runtime] --|> [Collections]
[Numerics] --|> [Runtime]
[Numerics] --|> [Globalization]
[Numerics] --|> [Text]
[Numerics] --|> [Reflection]
[Numerics] --|> [Diagnostics]
[Net] --|> [Globalization]
[Net] --|> [Buffers]
[Net] --|> [Text]
[Net] --|> [IO]
[Net] --|> [Diagnostics]
[Net] --|> [Collections]
[Globalization] --|> [Runtime]
[Globalization] --|> [Buffers]
[Globalization] --|> [Threading]
[Globalization] --|> [Text]
[Globalization] --|> [Reflection]
[Globalization] --|> [Diagnostics]
[Globalization] --|> [Collections]
[ComponentModel] --|> [Runtime]
[ComponentModel] --|> [Globalization]
[ComponentModel] --|> [Threading]
[ComponentModel] --|> [Text]
[ComponentModel] --|> [Reflection]
[ComponentModel] --|> [Diagnostics]
[CodeDom] --|> [Runtime]
[CodeDom] --|> [Globalization]
[CodeDom] --|> [Threading]
[CodeDom] --|> [Text]
[CodeDom] --|> [IO]
[CodeDom] --|> [Diagnostics]
[Buffers] --|> [Runtime]
[Buffers] --|> [Numerics]
[Buffers] --|> [Globalization]
[Buffers] --|> [CodeDom]
[Buffers] --|> [Threading]
[Buffers] --|> [Text]
[Buffers] --|> [Diagnostics]
[Buffers] --|> [Collections]
[Threading] --|> [Runtime]
[Threading] --|> [Globalization]
[Threading] --|> [CodeDom]
[Threading] --|> [Security]
[Threading] --|> [Reflection]
[Threading] --|> [IO]
[Threading] --|> [Diagnostics]
[Threading] --|> [Collections]
[Text] --|> [Runtime]
[Text] --|> [Numerics]
[Text] --|> [Globalization]
[Text] --|> [ComponentModel]
[Text] --|> [Buffers]
[Text] --|> [Threading]
[Text] --|> [Reflection]
[Text] --|> [IO]
[Text] --|> [Diagnostics]
[Text] --|> [Collections]
[StubHelpers] --|> [Runtime]
[StubHelpers] --|> [Text]
[Security] --|> [Runtime]
[Security] --|> [Threading]
[Security] --|> [Text]
[Security] --|> [Reflection]
[Security] --|> [Diagnostics]
[Security] --|> [Collections]
[Resources] --|> [Runtime]
[Resources] --|> [Globalization]
[Resources] --|> [ComponentModel]
[Resources] --|> [Buffers]
[Resources] --|> [Threading]
[Resources] --|> [Text]
[Resources] --|> [Reflection]
[Resources] --|> [IO]
[Resources] --|> [Diagnostics]
[Resources] --|> [Collections]
[Reflection] --|> [Runtime]
[Reflection] --|> [Globalization]
[Reflection] --|> [Configuration]
[Reflection] --|> [CodeDom]
[Reflection] --|> [Buffers]
[Reflection] --|> [Threading]
[Reflection] --|> [Text]
[Reflection] --|> [StubHelpers]
[Reflection] --|> [Security]
[Reflection] --|> [IO]
[Reflection] --|> [Diagnostics]
[Reflection] --|> [Collections]
[IO] --|> [Runtime]
[IO] --|> [Numerics]
[IO] --|> [Globalization]
[IO] --|> [ComponentModel]
[IO] --|> [Buffers]
[IO] --|> [Threading]
[IO] --|> [Text]
[IO] --|> [Reflection]
[IO] --|> [Diagnostics]
[IO] --|> [Collections]
[Diagnostics] --|> [Runtime]
[Diagnostics] --|> [Numerics]
[Diagnostics] --|> [Globalization]
[Diagnostics] --|> [ComponentModel]
[Diagnostics] --|> [CodeDom]
[Diagnostics] --|> [Buffers]
[Diagnostics] --|> [Threading]
[Diagnostics] --|> [Text]
[Diagnostics] --|> [Resources]
[Diagnostics] --|> [Reflection]
[Diagnostics] --|> [Collections]
[Collections] --|> [Runtime]
[Collections] --|> [Numerics]
[Collections] --|> [Globalization]
[Collections] --|> [ComponentModel]
[Collections] --|> [Buffers]
[Collections] --|> [Threading]
[Collections] --|> [Reflection]
[Collections] --|> [Diagnostics]
@enduml
