<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <IsPackable>false</IsPackable>
    <Product>TestAssembly</Product>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\strongNameKey.snk</AssemblyOriginatorKeyFile>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="TestAssembly.AssemblyTestAttribute">
      <_Parameter1>TestParameter</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
