site_name: ArchUnitNET
site_dir: site
docs_dir: docs

nav:
    - About: index.md
    - User Guide: guide.md
    - Additional: additional.md
    - Contribution: contributing.md
    - License: license.md

theme:
    name: readthedocs
    custom_dir: custom_theme/
