site_name: ArchUnitNET
site_dir: site
docs_dir: docs

nav:
    - User Guide: index.md
    - API: api.md
    - About: about.md
    - Contribution: contributing.md
    - License: license.md

theme: readthedocs
